app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');
//Route::get('/', 'HomeController@index');
Route::resource('lists', 'ListsController');
Route::get('contact', ['as' => 'contact', 'uses' => 'AboutController@create']);
Route::post('contact', ['as' => 'contact_store', 'uses' => 'AboutController@store']);
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');
Route::resource('lists.tasks', 'TasksController');

Route::post('lists/{lists}/tasks/{tasks}/complete',
    array('as' => 'complete_task', 'uses' => 'TasksController@complete'));

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');
});

app/Http/Controllers/ListsController.php
<?php

namespace todoparrot\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

use todoparrot\Http\Requests;
use todoparrot\Todolist;
use todoparrot\Http\Requests\ListFormRequest;
use todoparrot\Category;
use todoparrot\User;

class ListsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('listowner', ['only' => ['show', 'edit', 'update']]);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lists = User::find(\Auth::id())->lists()->orderBy('created_at', 'desc')->paginate(15);
        return view('lists.index')->with('lists', $lists);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::lists('name', 'id');

        return view('lists.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ListFormRequest $request)
    {
        $list = new Todolist(array(
            'name' => $request->get('name'),
            'description' => $request->get('description')
        ));

        $user = User::find(\Auth::id());
        $list = $user->lists()->save($list);


        return \Redirect::route('lists.index')->with('message', 'Your list has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $list = Todolist::find($id);
        return view('lists.show')->with('list', $list);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $list = Todolist::find($id);

        return view('lists.edit')->with('list', $list);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, ListFormRequest $request)
    {
        $user = \Auth::user();

        $list = Todolist::find($id);

        $list->update([
            'name' => $request->get('name'),
            'description' => $request->get('description')]);

        return \Redirect::route('lists.edit', array($list->id))->with('message', 'Your list has been updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Todolist::destroy($id);
        return \Redirect::route('lists.index')->with('message', 'The list has been deleted');
    }
}

resources/views/lists/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Create a New List</div>

                <div class="panel-body">

                    {!! Form::open(array('route' => 'lists.store', 'class' => 'form')) !!}
                    <div class ="form-group">
                        {!! Form::label('List Name') !!}
                        {!! Form::text('name', null, array('required', 'class' => 'form-control', 'placeholder' => 'San Juan Vacation')) !!}
                    </div>

                    <div class ="form-group">
                        {!! Form::label('List Description') !!}
                        {!! Form::textarea('description', null, array('required', 'class' => 'form-control', 'placeholder' => 'things to do before trip to San Juan')) !!}
                    </div>

                    <div class ="form-group">
                        {!! Form::submit('Create List', array('class'=> 'btn btn-primary')) !!}
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
    </div>



@endsection

resources/views/lists/edit.blade.php
@extends('layouts.app')

@section('content')

    {!! Form::model($list, array('method' => 'put', 'route' => ['lists.update', $list->id], 'class' => 'form')) !!}

    <div class ="form-group">
        {!! Form::label('List Name') !!}
        {!! Form::text('name', null, array('required', 'class' => 'form-control', 'placeholder' => 'List name')) !!}
    </div>

    <div class ="form-group">
        {!! Form::label('List Description') !!}
        {!! Form::textarea('description', null, array('required', 'class' => 'form-control', 'placeholder' => 'Your description')) !!}
    </div>

    <div class ="form-group">
        {!! Form::submit('Update List', array('class'=> 'btn btn-primary')) !!}
    </div>

    {!! Form::close() !!}


@endsection

resources/views/lists/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Lists</div>

                <div class="panel-body">
                    @if ($lists->count() > 0)
                        <ul>
                            @foreach ($lists as $list)
                                <li><a href="{{ url('/lists/' . $list->id) }}">{{ $list->name }} : {{$list->description}}</a></li>
                            @endforeach
                            {!! $lists->render() !!}
                        </ul>
                    @else
                        <p>
                            You don't have any lists. <br />
                            <a  href="{{ url('/lists/create') }}"
                               class = "btn btn-primary">Make one</a>

                        </p>
                    @endif
                </div>
            </div>
        </div>



@endsection

resources/views/lists/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3>{{$list->name}}</h3></div>

                    <div class="panel-body">
                        <h4>Description</h4>
                        <p>
                            {{ $list->description }}
                        </p>

                        <h4>Tasks</h4>
                        @if( $list->tasks->count() > 0)
                            <ul>
                                @foreach($list->tasks as $task)
                                    <li> {{ $task->name  }}</li>
                                @endforeach
                            </ul>
                            <p>
                                <a href="{{ URL::route('lists.tasks.create', [$list->id]) }}"
                                   class = "btn btn-primary">Add a new task</a>
                            </p>
                        @else
                            <p>
                                You haven't created any tasks. <br />
                                <a href="{{ URL::route('lists.tasks.create', [$list->id]) }}"
                                   class = "btn btn-primary">Create a task</a>
                            </p>
                        @endif
                        @foreach($list->comments as $comment)
                            <p>
                                {{$comment->body}}
                            </p>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection